# Generated by Django 3.0.1 on 2020-03-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200311_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_id',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
